name: Build and Upload


# build a single image, based on sbc and type inputs.
# uploads to artifacts and releases
# runs installer build if mirte-master
on:
  workflow_call:
    inputs:
        mirte_type:
            required: false
            type: string
            default: default
        sbc:
            required: false
            type: string
            default: orangepizero2
  workflow_dispatch:
    inputs:
        mirte_type:
            required: true
            type: choice
            default: default
            options:
              - default
              - mirte-master
        sbc:
            required: false
            type: choice
            default: orangepizero2
            options:
              - orangepizero2
              - orangepi3b
              - rpi4b

permissions:
    contents: write
  
jobs:
    build-and-push:
        # container:
        #   image: ubuntu:22.04
        #   options: --privileged
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Extract branch name
              shell: bash
              run: |
                echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
                echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_OUTPUT
                if [[ "${{ inputs.mirte_type }}" != "default" ]]; then
                    echo "artifact_name=${{ inputs.mirte_type }}_${{ inputs.sbc }}" | tr '-' '_' >> $GITHUB_OUTPUT
                else
                    echo "artifact_name=${{ inputs.sbc }}" >> $GITHUB_OUTPUT
                fi
              id: extract_branch
            - name: setup this repo
              run: |
                    sudo apt update
                    sudo apt install qemu-user-static parted -y
                    ./packerInstall.sh
            - name: setup build files
              run: |
                  echo -e "MIRTE_TYPE=${{ inputs.mirte_type }}" >> settings.sh
                  # cat settings.sh
                  # - name: setup repos
            #   run: |
            #     cp main_repos.yaml repos.yaml
            #     yq e -i '.repositories.mirte-ros-packages.version = "fix-intro-rob"' repos.yaml
            #     yq e -i '.repositories.mirte-telemetrix4arduino.url =  "https://github.com/arendjan/telemetrix4arduino.git"' repos.yaml
            #     yq e -i '.repositories.mirte-telemetrix4arduino.version = "fix-intro-robotics"' repos.yaml
            - name: Build
              run: |
                    ./packerBuild.sh ${{ inputs.sbc }}
            - name: artifacts
              uses: actions/upload-artifact@v4
              if: always()
              with:
                path: build/*.img.xz
                name: ${{ steps.extract_branch.outputs.artifact_name }}
            - name: Push to release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: build/*.img.xz

    # Only if mirte-master
    # upload_private_server:
    #   if: ${{ inputs.mirte_type == 'mirte-master' }} && false
    #   needs: [build-and-push]
    #   uses: ./.github/workflows/upload.yaml
    #   with:
    #     name: 'image'
    #   secrets: inherit

    build_installer_all:
      if: ${{ inputs.mirte_type == 'mirte-master' }}
      needs: [build-and-push]
      uses: ./.github/workflows/build_installer.yaml
      with:
        # download_artifacts: true
        sbc: ${{ inputs.sbc }}
      secrets: inherit
              